LiquidityEngineService:
  Name: Default
  WalletId:
    settings-key: LiquidityEngineService-WalletId
  Db:
    DataConnectionString:
      settings-key: LiquidityEngineService-DataConnectionString
      types:
      - AzureTableStorage

    LogsConnectionString:
      settings-key: LiquidityEngineService-LogsConnectionString
      types:
      - AzureTableStorage

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
      - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl