LiquidityEngineService:
  Name: Default
  
  WalletId:
    settings-key: LiquidityEngineService-WalletId
  
  Db:
    DataConnectionString:
      settings-key: LiquidityEngineService-DataConnectionString
      types:
      - AzureTableStorage

    LogsConnectionString:
      settings-key: LiquidityEngineService-LogsConnectionString
      types:
      - AzureTableStorage
  
  Rabbit:
    Subscribers:
      LykkeTrades:
        ConnectionString:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-ConnectionString
          types:
          - RabbitMq
        Exchange:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-Exchange
        Queue:
          settings-key: LiquidityEngineService-Rabbit-Subscribers-LykkeTrades-Queue

BalancesServiceClient:
  ServiceUrl:
    settings-key: BalancesServiceUrl
    
ExchangeOperationsServiceClient:
  ServiceUrl:
    settings-key: ExchangeOperationsServiceUrl
    
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
      - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl